force-app/main/default/objects/Attendance__c/Attendance__c.object-meta.xml
<CustomObject>
    <label>Attendance</label>
    <nameField>
        <displayFormat>V2#{000}</displayFormat>
        <label>Attendance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendance__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>DATE( YEAR(TODAY() ), MONTH(TODAY() ), Day(TODAY() ))</defaultValue>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Present__c.field-meta.xml
<CustomField>
    <fullName>Present__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Present</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Trainee_Name__c.field-meta.xml
<CustomField>
    <fullName>Trainee_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Trainee Name</label>
    <referenceTo>Trainee__c</referenceTo>
    <relationshipLabel>Attendance</relationshipLabel>
    <relationshipName>Attendance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Training_Name__c.field-meta.xml
<CustomField>
    <fullName>Training_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Training Name</label>
    <referenceTo>New_Training__c</referenceTo>
    <relationshipLabel>Attendance</relationshipLabel>
    <relationshipName>Attendance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/New_Training__c/New_Training__c.object-meta.xml
<CustomObject>
    <label>New Training</label>
    <nameField>
        <label>New Training Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>New Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trainee__c/Trainee__c.object-meta.xml
<CustomObject>
    <label>Trainee</label>
    <nameField>
        <label>Trainee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trainee_Participate__c/Trainee_Participate__c.object-meta.xml
<CustomObject>
    <label>Trainee Participate</label>
    <nameField>
        <displayFormat>V2Trainee#{000000}</displayFormat>
        <label>Trainee Participate ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trainee Participates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trainee_Participate__c/fields/Trainee_Name__c.field-meta.xml
<CustomField>
    <fullName>Trainee_Name__c</fullName>
    <label>Trainee Name</label>
    <referenceTo>Trainee__c</referenceTo>
    <relationshipLabel>Trainee Participates</relationshipLabel>
    <relationshipName>Trainee_Participates</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trainee_Participate__c/fields/Training_Name__c.field-meta.xml
<CustomField>
    <fullName>Training_Name__c</fullName>
    <label>Training Name</label>
    <referenceTo>New_Training__c</referenceTo>
    <relationshipLabel>Trainee Participates</relationshipLabel>
    <relationshipName>Trainee_Participates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CurrentTraineeAttendance.cls
public with sharing class CurrentTraineeAttendance {

    @AuraEnabled       
    public static List<Trainee_Participate__c> CurrentAttendees(String trainingID){
         List<Trainee_Participate__c>  TraineeList = [SELECT Trainee_Name__c,Trainee_Name__r.Name
                                                      FROM Trainee_Participate__c WHERE Training_Name__c =:trainingID];
        return TraineeList;
    }
    @AuraEnabled
    public static List<New_Training__c> fetchTrainingNamesFromApex()
    {
        List<New_Training__c> trainingRecords = [Select Id,Name FROM New_Training__c];
        return trainingRecords;      
    }
    
    @AuraEnabled
    public static String insertAttendanceApex(Id trainingID, List<Id> absenteeIDS,List<Id> presentIDS,String AttendanceDate)
    {
        Date trainingAttendanceDate =  Date.valueOf(AttendanceDate);
        List<Attendance__c> lstAttendanceToBeProcessed = new List<Attendance__c>();
        if(absenteeIDS != null || !absenteeIDS.isEmpty())
        {
            for(Id absentee : absenteeIDS)
            {
                Attendance__c attendance = new Attendance__c(
                    Trainee_Name__c = absentee,
                    Training_Name__c = trainingID,
                    Present__c =False,
                    Date__c = trainingAttendanceDate
                );
                lstAttendanceToBeProcessed.add(attendance);
            }
        }
        if(presentIDS != null || !presentIDS.isEmpty())
        {
            for(Id present : presentIDS)
            {
                Attendance__c attendance = new Attendance__c(
                    Trainee_Name__c = present,
                    Training_Name__c = trainingID,
                    Date__c = trainingAttendanceDate
                );
                lstAttendanceToBeProcessed.add(attendance);
            }
        }
        insert lstAttendanceToBeProcessed;
        return 'Success';
		    
    }

}