force-app/main/default/objects/New_Training__c/New_Training__c.object-meta.xml
<CustomObject>
    <label>New Training</label>
    <nameField>
        <label>New Training Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>New Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trainee__c/Trainee__c.object-meta.xml
<CustomObject>
    <label>Trainee</label>
    <nameField>
        <label>Trainee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trainee__c/fields/Competency_1__c.field-meta.xml
<CustomField>
    <fullName>Competency_1__c</fullName>
    <label>Competency 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Competency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trainee__c/fields/Competency_2__c.field-meta.xml
<CustomField>
    <fullName>Competency_2__c</fullName>
    <label>Competency 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Competency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trainee__c/fields/Evaluation_Performance__c.field-meta.xml
<CustomField>
    <fullName>Evaluation_Performance__c</fullName>
    <label>Evaluation Performance</label>
    <summarizedField>Trainee_Evaluation__c.Total_Percent__c</summarizedField>
    <summaryForeignKey>Trainee_Evaluation__c.Trainee_Name__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Trainee__c/fields/General_Awareness_Performance__c.field-meta.xml
<CustomField>
    <fullName>General_Awareness_Performance__c</fullName>
    <label>General Awareness Performance</label>
    <summarizedField>Trainee_General_Evaluation__c.Average_Skill__c</summarizedField>
    <summaryForeignKey>Trainee_General_Evaluation__c.Trainee__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Trainee__c/fields/Office_Location__c.field-meta.xml
<CustomField>
    <fullName>Office_Location__c</fullName>
    <label>Office-Location</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>India-Bengaluru</fullName>
            </value>
            <value>
                <fullName>India-Bhuvneshwar</fullName>
            </value>
            <value>
                <fullName>India-Mumbai</fullName>
            </value>
            <value>
                <fullName>India-Udaipur</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trainee__c/fields/Trailhead_Badges__c.field-meta.xml
<CustomField>
    <fullName>Trailhead_Badges__c</fullName>
    <label>Trailhead Badges</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trainee__c/fields/Trailhead_Profile__c.field-meta.xml
<CustomField>
    <fullName>Trailhead_Profile__c</fullName>
    <label>Trailhead Profile</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Trainee_Participate__c/Trainee_Participate__c.object-meta.xml
<CustomObject>
    <label>Trainee Participate</label>
    <nameField>
        <displayFormat>V2Trainee#{000000}</displayFormat>
        <label>Trainee Participate ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trainee Participates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trainee_Participate__c/fields/Trainee_Name__c.field-meta.xml
<CustomField>
    <fullName>Trainee_Name__c</fullName>
    <label>Trainee Name</label>
    <referenceTo>Trainee__c</referenceTo>
    <relationshipLabel>Trainee Participates</relationshipLabel>
    <relationshipName>Trainee_Participates</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trainee_Participate__c/fields/Training_Name__c.field-meta.xml
<CustomField>
    <fullName>Training_Name__c</fullName>
    <label>Training Name</label>
    <referenceTo>New_Training__c</referenceTo>
    <relationshipLabel>Trainee Participates</relationshipLabel>
    <relationshipName>Trainee_Participates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Competency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Apex Programming</fullName>
    </customValue>
    <customValue>
        <fullName>BA</fullName>
    </customValue>
    <customValue>
        <fullName>Community</fullName>
    </customValue>
    <customValue>
        <fullName>Config/Admin</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer Goods</fullName>
    </customValue>
    <customValue>
        <fullName>CPQ</fullName>
    </customValue>
    <customValue>
        <fullName>Einstein Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>Force.com</fullName>
    </customValue>
    <customValue>
        <fullName>FSL</fullName>
    </customValue>
    <customValue>
        <fullName>FSL &amp; Config/Admin</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>Marketting Cloud/Consumer Goods</fullName>
    </customValue>
    <customValue>
        <fullName>Pardot</fullName>
    </customValue>
    <customValue>
        <fullName>Pardot &amp; Config/Admin</fullName>
    </customValue>
    <customValue>
        <fullName>QA</fullName>
    </customValue>
    <customValue>
        <fullName>UI/UX</fullName>
    </customValue>
    <customValue>
        <fullName>Vlocity Omni</fullName>
    </customValue>
    <masterLabel>Competency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CurrentTraineeList.cls
public class CurrentTraineeList {
    @AuraEnabled
    public static List<Trainee_Participate__c> GetCurrentTrainee(String trainingName)
    {
        
        String trainingNameQuery;
        List<Trainee_Participate__c>  lstTrainee ;
        if(String.isEmpty(trainingName))
        {
            lstTrainee = [SELECT Id, Training_Name__r.Name,Trainee_Name__r.Name,Trainee_Name__r.Office_Location__c,
                          Trainee_Name__r.Trailhead_Profile__c, Trainee_Name__r.Trailhead_Badges__c,Trainee_Name__r.Competency_1__c,Trainee_Name__r.Competency_2__c,Trainee_Name__r.General_Awareness_Performance__c,Trainee_Name__r.Evaluation_Performance__c 
                          FROM Trainee_Participate__c WHERE Training_Name__c in :[Select Id FROM New_Training__c WHERE End_Date__c = null] And Trainee_Name__r.Active__c = True Order By Trainee_Name__r.Name ];  
        }
        else
        {
            lstTrainee = [SELECT Id, Training_Name__r.Name,Trainee_Name__r.Name,Trainee_Name__r.Office_Location__c,
                          Trainee_Name__r.Trailhead_Profile__c, Trainee_Name__r.Trailhead_Badges__c,Trainee_Name__r.Competency_1__c,Trainee_Name__r.Competency_2__c 
                          FROM Trainee_Participate__c WHERE Training_Name__c =:trainingName And Trainee_Name__r.Active__c = True Order By Trainee_Name__r.Name];  
        }
        
        return lstTrainee;
    } 
}