force-app/main/default/objects/New_Training__c/New_Training__c.object-meta.xml
<CustomObject>
    <label>New Training</label>
    <nameField>
        <label>New Training Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>New Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/New_Training__c/fields/Trainer_Name__c.field-meta.xml
<CustomField>
    <fullName>Trainer_Name__c</fullName>
    <label>Trainer Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/New_Training__c/fields/Training__c.field-meta.xml
<CustomField>
    <fullName>Training__c</fullName>
    <label>Training</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Training</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trainee__c/Trainee__c.object-meta.xml
<CustomObject>
    <label>Trainee</label>
    <nameField>
        <label>Trainee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trainee__c/fields/Office_Location__c.field-meta.xml
<CustomField>
    <fullName>Office_Location__c</fullName>
    <label>Office-Location</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>India-Bengaluru</fullName>
            </value>
            <value>
                <fullName>India-Bhuvneshwar</fullName>
            </value>
            <value>
                <fullName>India-Mumbai</fullName>
            </value>
            <value>
                <fullName>India-Udaipur</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trainee_Participate__c/Trainee_Participate__c.object-meta.xml
<CustomObject>
    <label>Trainee Participate</label>
    <nameField>
        <displayFormat>V2Trainee#{000000}</displayFormat>
        <label>Trainee Participate ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trainee Participates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trainee_Participate__c/fields/Trainee_Name__c.field-meta.xml
<CustomField>
    <fullName>Trainee_Name__c</fullName>
    <label>Trainee Name</label>
    <referenceTo>Trainee__c</referenceTo>
    <relationshipLabel>Trainee Participates</relationshipLabel>
    <relationshipName>Trainee_Participates</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trainee_Participate__c/fields/Training_Name__c.field-meta.xml
<CustomField>
    <fullName>Training_Name__c</fullName>
    <label>Training Name</label>
    <referenceTo>New_Training__c</referenceTo>
    <relationshipLabel>Trainee Participates</relationshipLabel>
    <relationshipName>Trainee_Participates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Training_Plan__c/Training_Plan__c.object-meta.xml
<CustomObject>
    <label>Standard Training Plan</label>
    <nameField>
        <displayFormat>V2Training#{00000}</displayFormat>
        <label>Training Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Standard Training Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Plan__c/fields/Day__c.field-meta.xml
<CustomField>
    <fullName>Day__c</fullName>
    <label>Day</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Training_Plan__c/fields/Topic_Name__c.field-meta.xml
<CustomField>
    <fullName>Topic_Name__c</fullName>
    <label>Topic Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Training_Plan__c/fields/Training_Name__c.field-meta.xml
<CustomField>
    <fullName>Training_Name__c</fullName>
    <label>Training Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Training</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Training.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Administrator</fullName>
    </customValue>
    <customValue>
        <fullName>CPQ</fullName>
    </customValue>
    <customValue>
        <fullName>Developer</fullName>
    </customValue>
    <customValue>
        <fullName>Integration</fullName>
    </customValue>
    <customValue>
        <fullName>Lightning Component</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing</fullName>
    </customValue>
    <masterLabel>Training</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CurrentTraineeAttendance_Test.cls
@isTest
public class CurrentTraineeAttendance_Test {
    @testSetup 
    static void testData() 
    {
        Training_Plan__c test1 = new Training_Plan__c(
            Training_Name__C = 'Administrator',
            Day__c =1,
            Topic_Name__C = 'Test Topic 1');
        
        insert test1;
        
        Training_Plan__c test2 = new Training_Plan__c(
            Training_Name__C = 'Administrator',
            Day__c =2,
            Topic_Name__C = 'Test Topic 2');
        
        insert test2;
        
        New_Training__c testNewTraining = new New_Training__c(
            Name = 'Test Admin Training',
            Trainer_Name__c = 'Test Trainer',
            Start_Date__c= System.Today(),
            Training__C = 'Administrator');
        
        insert testNewTraining;
        
        Trainee__c testTrainee1 = new Trainee__c(
            Name = 'Test Trainee1',
            Office_Location__c = 'India-Udaipur');
        
        insert testTrainee1;
        
        Trainee__c testTrainee2 = new Trainee__c(
            Name = 'Test Trainee2',
            Office_Location__c = 'India-Udaipur');
        
        insert testTrainee2;
        
        Trainee_Participate__c testTraineeParticipate1 = new Trainee_Participate__c(
            Training_Name__c = testNewTraining.Id,
            Trainee_Name__c = testTrainee1.Id);
        
        insert testTraineeParticipate1;
        
        Trainee_Participate__c testTraineeParticipate2 = new Trainee_Participate__c(
            Training_Name__c = testNewTraining.Id,
            Trainee_Name__c = testTrainee2.Id);
        
        insert testTraineeParticipate2;        
        
        Trainee_Participate__c testTraineeParticipate3 = new Trainee_Participate__c(
            Training_Name__c = testNewTraining.Id,
            Trainee_Name__c = testTrainee2.Id);
        
        try
        {
            insert testTraineeParticipate3;
        }
        catch(Exception e)
        {
            System.assertEquals(e.getMessage().contains('The selected trainee already in the selected training'),true );
        }
    }
    
    @isTest
    static void testFunctions()
    {
        List<New_Training__c> testTrainingList = new List<New_Training__c>();
        List<Trainee_Participate__c> testtraineeParticpate1 = new List<Trainee_Participate__c>();
        String result;
        Test.startTest();
        testTrainingList = CurrentTraineeAttendance.fetchTrainingNamesFromApex();
        testtraineeParticpate1 = CurrentTraineeAttendance.CurrentAttendees(testTrainingList[0].Id);
        result = CurrentTraineeAttendance.insertAttendanceApex(testTrainingList[0].Id, new List<Id>{testtraineeParticpate1[0].Trainee_Name__c}, 
                                                               new List<Id>{testtraineeParticpate1[1].Trainee_Name__c}, String.valueOf(System.today()));
        Test.stopTest();
        
        System.assertEquals('Success', result);
    }
    
    
}