force-app/main/default/objects/New_Training__c/New_Training__c.object-meta.xml
<CustomObject>
    <label>New Training</label>
    <nameField>
        <label>New Training Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>New Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/New_Training__c/fields/Number_of_Trainee__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Trainee__c</fullName>
    <label>Number of Trainee</label>
    <summaryForeignKey>Trainee_Participate__c.Training_Name__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/New_Training__c/fields/Trainer_Name__c.field-meta.xml
<CustomField>
    <fullName>Trainer_Name__c</fullName>
    <label>Trainer Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/New_Training_Plan__c/New_Training_Plan__c.object-meta.xml
<CustomObject>
    <label>Training Plan</label>
    <nameField>
        <label>Topic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/New_Training_Plan__c/fields/Day__c.field-meta.xml
<CustomField>
    <fullName>Day__c</fullName>
    <label>Day</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/New_Training_Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/New_Training_Plan__c/fields/Training_Name__c.field-meta.xml
<CustomField>
    <fullName>Training_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training Name</label>
    <referenceTo>New_Training__c</referenceTo>
    <relationshipLabel>Training Plans</relationshipLabel>
    <relationshipName>New_Training_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TrainingStatusCC.cls
public class TrainingStatusCC {
    @AuraEnabled
    public static List<New_Training__c> fetchTrainingNamesFromApex()
    {
        List<New_Training__c> trainingRecords = [Select Id,Name,Trainer_Name__c,Start_Date__c,Number_of_Trainee__c FROM New_Training__c];
        return trainingRecords;      
    }
    
    @AuraEnabled
    public static List<New_Training_Plan__c> fetchTrainingRecords(String recordId)
    {
        List<New_Training_Plan__c> trainingRecords = [Select Id,Name,Status__c,Completion_Date__c,Day__c FROM New_Training_Plan__c WHERE Training_Name__c = :recordId Order By Day__c];
        return trainingRecords;      
    }
    
}