force-app/main/default/objects/New_Training__c/New_Training__c.object-meta.xml
<CustomObject>
    <label>New Training</label>
    <nameField>
        <label>New Training Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>New Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/New_Training__c/fields/Training__c.field-meta.xml
<CustomField>
    <fullName>Training__c</fullName>
    <label>Training</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Training</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/New_Training_Plan__c/New_Training_Plan__c.object-meta.xml
<CustomObject>
    <label>Training Plan</label>
    <nameField>
        <label>Topic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/New_Training_Plan__c/fields/Day__c.field-meta.xml
<CustomField>
    <fullName>Day__c</fullName>
    <label>Day</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/New_Training_Plan__c/fields/Training_Name__c.field-meta.xml
<CustomField>
    <fullName>Training_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training Name</label>
    <referenceTo>New_Training__c</referenceTo>
    <relationshipLabel>Training Plans</relationshipLabel>
    <relationshipName>New_Training_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training_Plan__c/Training_Plan__c.object-meta.xml
<CustomObject>
    <label>Standard Training Plan</label>
    <nameField>
        <displayFormat>V2Training#{00000}</displayFormat>
        <label>Training Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Standard Training Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Plan__c/fields/Day__c.field-meta.xml
<CustomField>
    <fullName>Day__c</fullName>
    <label>Day</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Training_Plan__c/fields/Topic_Name__c.field-meta.xml
<CustomField>
    <fullName>Topic_Name__c</fullName>
    <label>Topic Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Training_Plan__c/fields/Training_Name__c.field-meta.xml
<CustomField>
    <fullName>Training_Name__c</fullName>
    <label>Training Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Training</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Training.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Administrator</fullName>
    </customValue>
    <customValue>
        <fullName>CPQ</fullName>
    </customValue>
    <customValue>
        <fullName>Developer</fullName>
    </customValue>
    <customValue>
        <fullName>Integration</fullName>
    </customValue>
    <customValue>
        <fullName>Lightning Component</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing</fullName>
    </customValue>
    <masterLabel>Training</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TrainingTriggerHandler.cls
public class TrainingTriggerHandler {
    
    public static void preparedTrainingPlan(List<New_Training__c> lstNewTraining)
    {
        List<New_Training_Plan__c> trainingPlanToBeProcessed = new List<New_Training_Plan__c>();
        map<Id,Training_Plan__c> mapStoredTrainingPlan = new map<Id,Training_Plan__c>([SELECT Id, Topic_Name__c, Training_Name__c,Day__c FROM Training_Plan__c]); 
        
        if(!mapStoredTrainingPlan.isEmpty())
        {
            for(New_Training__c obj : lstNewTraining)
            {
                for(Training_Plan__c trainingPlanObj : mapStoredTrainingPlan.values())
                {
                    if(trainingPlanObj.Training_Name__c == obj.Training__c)
                    {
                        New_Training_Plan__c NewTrainingPlanobj = new New_Training_Plan__c(
                            
                            Training_Name__c = obj.Id,
                            Name= trainingPlanObj.Topic_Name__c,
                            Day__c = trainingPlanObj.Day__c
                        );
                        trainingPlanToBeProcessed.add(NewTrainingPlanobj );                                    
                    }                                    
                }                               
            }
            if(trainingPlanToBeProcessed != null || !trainingPlanToBeProcessed.isEmpty())
            {
                insert trainingPlanToBeProcessed;              
            }                      
        }
    }
}